import type { Metadata } from "next";
import { Chelsea_Market, Chewy } from "next/font/google";
import "./globals.scss";
import { CSSProperties } from "react";
import Interface from "./layout/interface/Interface";

const chelsea = Chelsea_Market({ subsets: ["latin"], weight: "400" });
const chewy = Chewy({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Deliciarin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={chelsea.className}
        style={
          {
            "--fontMain": chelsea.style.fontFamily,
            "--fontAlt": chewy.style.fontFamily,
          } as CSSProperties
        }
      >
        <Interface />
        {children}
      </body>
    </html>
  );
}
